// Native Rust translation of the used OTM normalized LBR 1.0.0.1520 functions.
// Generated by scripts/generate_lbr_fallback.py from the retained original C++ AST.
// Copyright © 2013-2024 Peter Jäckel.
// Permission to use, copy, modify, and distribute this software is freely granted,
// provided that this notice is preserved.
// WARRANTY DISCLAIMER
// The Software is provided "as is" without warranty of any kind, either express
// or implied, including without limitation any implied warranties of condition,
// uninterrupted use, merchantability, fitness for a particular purpose, or
// non-infringement.
// Retain typed AST grouping, original coefficients, branch spelling, helper
// signatures and explicit returns so the numerical source remains auditable.
#![allow(
    unused_mut,
    unused_parens,
    non_snake_case,
    non_upper_case_globals,
    unused_assignments
)]
#![allow(
    clippy::double_parens,
    clippy::needless_return,
    clippy::approx_constant,
    clippy::too_many_arguments,
    clippy::neg_cmp_op_on_partial_ord
)]
use crate::experimental::math::inverse_norm_cdf_unfused as inverse_norm_cdf;
use crate::experimental::math::{erfc_cody, erfcx_cody, erfinv_unfused as erfinv};
fn cxx_max(a: f64, b: f64) -> f64 {
    if a < b { b } else { a }
}
pub(crate) fn solve(a: f64, b: f64) -> f64 {
    lets_be_rational(b, -a.abs(), 2)
}

const VOLATILITY_VALUE_TO_SIGNAL_PRICE_IS_BELOW_INTRINSIC: f64 = -1.7976931348623157e+308;
const VOLATILITY_VALUE_TO_SIGNAL_PRICE_IS_ABOVE_MAXIMUM: f64 = 1.7976931348623157e+308;
const SIXTEENTH_ROOT_DBL_EPSILON: f64 = 0.10511205190671433;
const SQRT_DBL_MAX: f64 = 1.3407807929942596e+154;
const minimum_rational_cubic_control_parameter_value: f64 = -0.9999999850988388;
const maximum_rational_cubic_control_parameter_value: f64 = 4.056481920730334e+31;

#[rustfmt::skip]
fn lets_be_rational(mut beta: f64, mut thetax: f64, mut N: i32) -> f64 {

if (beta <= 0.0_f64) {
return implied_volatility_output(0, (if (0.0_f64 == beta) { 0.0_f64 } else { VOLATILITY_VALUE_TO_SIGNAL_PRICE_IS_BELOW_INTRINSIC }));
}
let mut bmax: f64 = ((0.5_f64 * thetax)).exp();
if (beta >= bmax) {
return implied_volatility_output(0, VOLATILITY_VALUE_TO_SIGNAL_PRICE_IS_ABOVE_MAXIMUM);
}
if (0.0_f64 == thetax) {
return ((2.0_f64 * 1.4142135623730951_f64) * erfinv(beta));
}
let mut iterations: i32 = 0;
let mut f: f64 = (-1.7976931348623157e+308_f64);
let mut s: f64 = (-1.7976931348623157e+308_f64);
let mut ds: f64 = (-1.7976931348623157e+308_f64);
let mut sqrt_ax: f64 = ((-thetax)).sqrt();
let mut s_c: f64 = (1.4142135623730951_f64 * sqrt_ax);
let mut ome: f64 = one_minus_erfcx(sqrt_ax);
let mut b_c: f64 = ((0.5_f64 * bmax) * ome);
if (beta < b_c) {

let mut sl: f64 = (s_c - (1.2533141373155003_f64 * ome));

let mut bl: f64 = (bl_over_bmax(s_c) * bmax);
if (beta < bl) {
{
let mut f_lower_map_l: f64 = 0.0;
let mut d_f_lower_map_l_d_beta: f64 = 0.0;
let mut d2_f_lower_map_l_d_beta2: f64 = 0.0;
compute_f_lower_map_and_first_two_derivatives(thetax, sl, &mut f_lower_map_l, &mut d_f_lower_map_l_d_beta, &mut d2_f_lower_map_l_d_beta2);
let mut rll: f64 = convex_rational_cubic_control_parameter_to_fit_second_derivative_at_right_side(0.0_f64, bl, 0.0_f64, f_lower_map_l, 1.0_f64, d_f_lower_map_l_d_beta, d2_f_lower_map_l_d_beta2, true);
(f = rational_cubic_interpolation(beta, 0.0_f64, bl, 0.0_f64, f_lower_map_l, 1.0_f64, d_f_lower_map_l_d_beta, rll));
if (!(f > 0.0_f64)) {
let mut t: f64 = (beta / bl);
(f = (((f_lower_map_l * t) + (bl * (1.0_f64 - t))) * t));
}
(s = inverse_f_lower_map(thetax, f));
}

let mut ln_beta: f64 = (beta).ln();
{

while ((iterations < N) && ((ds).abs() > (2.220446049250313e-16_f64 * s))) {
{

let (bx, ln_vega) = scaled_normalised_black_and_ln_vega(thetax, s);
let mut ln_b: f64 = ((bx).ln() + ln_vega);
let mut bpob: f64 = (1.0_f64 / bx);
{
let mut h: f64 = (thetax / s);
let mut x_sqr_over_s_cube: f64 = ((h * h) / s);
let mut b_h2: f64 = (x_sqr_over_s_cube - (s / 4.0_f64));
let mut nu: f64 = ((((ln_beta - ln_b) * ln_b) / ln_beta) / bpob);
let mut lambda: f64 = (1.0_f64 / ln_b);
let mut otlambda: f64 = (1.0_f64 + (2.0_f64 * lambda));
let mut h2: f64 = (b_h2 - (bpob * otlambda));
let mut c: f64 = (3.0_f64 * (x_sqr_over_s_cube / s));
let mut b_h3: f64 = (((b_h2 * b_h2) - c) - 0.25_f64);
let mut sq_bpob: f64 = (bpob * bpob);
let mut bppob: f64 = (b_h2 * bpob);
let mut mu: f64 = ((6.0_f64 * lambda) * (1.0_f64 + lambda));
let mut h3: f64 = ((b_h3 + (sq_bpob * (2.0_f64 + mu))) - ((bppob * 3.0_f64) * otlambda));
if (thetax < ((-190) as f64)) {
(ds = (nu * householder_factor4(nu, h2, h3, (((((b_h2 * (b_h3 - 0.5_f64)) - (((b_h2 - (2.0_f64 / s)) * 2.0_f64) * c)) - (bpob * ((sq_bpob * (6.0_f64 + (lambda * (22.0_f64 + (lambda * (36.0_f64 + (lambda * 24.0_f64))))))) - (bppob * (12.0_f64 + (6.0_f64 * mu)))))) - (((bppob * b_h2) * 3.0_f64) * otlambda)) - (((b_h3 * bpob) * 4.0_f64) * otlambda)))));
} else {
(ds = (nu * householder_factor3(nu, h2, h3)));
}
}
(s += ds);

}
(iterations += 1);
}
}
return implied_volatility_output(iterations, s);
} else {
let mut inv_v_c: f64 = (2.5066282746310007_f64 / bmax);
let mut inv_vl: f64 = inv_normalised_vega(thetax, sl);
let mut rlm: f64 = convex_rational_cubic_control_parameter_to_fit_second_derivative_at_right_side(bl, b_c, sl, s_c, inv_vl, inv_v_c, 0.0_f64, false);
(s = rational_cubic_interpolation(beta, bl, b_c, sl, s_c, inv_vl, inv_v_c, rlm));

}
} else {
let mut su: f64 = (s_c + (1.2533141373155003_f64 * (2.0_f64 - ome)));

let mut bu: f64 = (bu_over_bmax(s_c) * bmax);
if (beta <= bu) {
let mut inv_v_c: f64 = (2.5066282746310007_f64 / bmax);
let mut inv_vu: f64 = inv_normalised_vega(thetax, su);
let mut rum: f64 = convex_rational_cubic_control_parameter_to_fit_second_derivative_at_left_side(b_c, bu, s_c, su, inv_v_c, inv_vu, 0.0_f64, false);
(s = rational_cubic_interpolation(beta, b_c, bu, s_c, su, inv_v_c, inv_vu, rum));

} else {
let mut f_upper_map_h: f64 = 0.0;
let mut d_f_upper_map_h_d_beta: f64 = 0.0;
let mut d2_f_upper_map_h_d_beta2: f64 = 0.0;
compute_f_upper_map_and_first_two_derivatives(thetax, su, &mut f_upper_map_h, &mut d_f_upper_map_h_d_beta, &mut d2_f_upper_map_h_d_beta2);
if ((d2_f_upper_map_h_d_beta2 > (-SQRT_DBL_MAX)) && (d2_f_upper_map_h_d_beta2 < SQRT_DBL_MAX)) {
let mut ruu: f64 = convex_rational_cubic_control_parameter_to_fit_second_derivative_at_left_side(bu, bmax, f_upper_map_h, 0.0_f64, d_f_upper_map_h_d_beta, (-0.5_f64), d2_f_upper_map_h_d_beta2, true);
(f = rational_cubic_interpolation(beta, bu, bmax, f_upper_map_h, 0.0_f64, d_f_upper_map_h_d_beta, (-0.5_f64), ruu));
}
if (f <= 0.0_f64) {
let mut h: f64 = (bmax - bu);
let mut t: f64 = ((beta - bu) / h);
(f = (((f_upper_map_h * (1.0_f64 - t)) + ((0.5_f64 * h) * t)) * (1.0_f64 - t)));
}
(s = inverse_f_upper_map(f));

if (beta > (0.5_f64 * bmax)) {
let mut beta_bar: f64 = (bmax - beta);
{

while ((iterations < N) && ((ds).abs() > (2.220446049250313e-16_f64 * s))) {
{
let mut h: f64 = (thetax / s);
let mut t: f64 = (s / 2.0_f64);
let mut gp: f64 = ((2.0_f64 / 2.5066282746310007_f64) / (erfcx_cody(((t + h) * (1.0_f64 / 1.4142135623730951_f64))) + erfcx_cody(((t - h) * (1.0_f64 / 1.4142135623730951_f64)))));
let mut b_bar: f64 = (normalised_vega(thetax, s) / gp);
{
let mut g: f64 = ((beta_bar / b_bar)).ln();
let mut x_sqr_over_s_cube: f64 = ((h * h) / s);
let mut b_h2: f64 = (x_sqr_over_s_cube - (s / 4.0_f64));
let mut c: f64 = (3.0_f64 * (x_sqr_over_s_cube / s));
let mut b_h3: f64 = (((b_h2 * b_h2) - c) - 0.25_f64);
let mut nu: f64 = ((-g) / gp);
let mut h2: f64 = (b_h2 + gp);
let mut h3: f64 = (b_h3 + (gp * ((2.0_f64 * gp) + (3.0_f64 * b_h2))));
if (thetax < ((-580) as f64)) {
(ds = (nu * householder_factor4(nu, h2, h3, (((b_h2 * (b_h3 - 0.5_f64)) - (((b_h2 - (2.0_f64 / s)) * 2.0_f64) * c)) + (gp * ((((6.0_f64 * gp) * (gp + (2.0_f64 * b_h2))) + ((3.0_f64 * b_h2) * b_h2)) + (4.0_f64 * b_h3)))))));
} else {
(ds = (nu * householder_factor3(nu, h2, h3)));
}
}
(s += ds);

}
(iterations += 1);
}
}
return implied_volatility_output(iterations, s);
}
}
}
{

while ((iterations < N) && ((ds).abs() > (2.220446049250313e-16_f64 * s))) {
{

let mut b: f64 = normalised_black(thetax, s);
let mut inv_bp: f64 = inv_normalised_vega(thetax, s);
let mut nu: f64 = ((beta - b) * inv_bp);
let mut h: f64 = (thetax / s);
let mut x_sqr_over_s_cube: f64 = ((h * h) / s);
let mut h2: f64 = (x_sqr_over_s_cube - (s * 0.25_f64));
let mut h3: f64 = (((h2 * h2) - (3.0_f64 * (x_sqr_over_s_cube / s))) - 0.25_f64);
(ds = (nu * householder_factor3(nu, h2, h3)));
(s += ds);

}
(iterations += 1);
}
}
return implied_volatility_output(iterations, s);
}

#[rustfmt::skip]
fn bu_over_bmax(mut s_c: f64) -> f64 {
if (s_c < 1.7888543819998317_f64) {
if (s_c < 0.7745966692414833_f64) {
let mut g: f64 = (((-0.060630998812335614_f64) + (s_c * ((-0.08101194663712061_f64) + (s_c * ((-0.042505564862438755_f64) + (s_c * ((-0.008988000094686869_f64) + (s_c * ((-7.560307211044327e-06_f64) + (4.387955662154015e-07_f64 * s_c)))))))))) / (1.0_f64 + (s_c * (1.8400371530721829_f64 + (s_c * (1.5709283443886144_f64 + (s_c * (0.689132454536114_f64 + (0.1470317306172098_f64 * s_c)))))))));
return (0.7899085945560628_f64 + ((s_c * s_c) * (0.06146168058051474_f64 + (s_c * g))));
}
return ((0.7899094443575528_f64 + (s_c * ((-1.2655410534988973_f64) + (s_c * ((-2.8803040699221003_f64) + (s_c * ((-2.693619868911326_f64) + (s_c * ((-1.1213067281643205_f64) + (s_c * ((-0.2127779380169163_f64) + (5.14864459052998e-06_f64 * s_c)))))))))))) / (1.0_f64 + (s_c * ((-1.6021222722060444_f64) + (s_c * ((-3.7242680976480704_f64) + (s_c * ((-3.2083117718907364_f64) + (s_c * ((-1.292233383593096_f64) - (0.2376232833405_f64 * s_c)))))))))));
}
if (s_c < 6.164414002968976_f64) {
return ((0.789906400489676_f64 + (s_c * (1.5993699253596663_f64 + (s_c * (1.648172903914037_f64 + (s_c * (0.982271881098692_f64 + (s_c * (0.3631355796618694_f64 + (s_c * (0.0782770362611796_f64 + (0.009340430736453872_f64 * s_c)))))))))))) / (1.0_f64 + (s_c * (2.02474070056404_f64 + (s_c * (2.008745427910374_f64 + (s_c * (1.1627561803056963_f64 + (s_c * (0.42004672123723824_f64 + (s_c * (0.08913086279388724_f64 + (0.010436767768858022_f64 * s_c)))))))))))));
}
return ((0.7911338259484194_f64 + (s_c * (1.2465373321088005_f64 + (s_c * (1.3274742698053739_f64 + (s_c * (0.6950097057178468_f64 + (s_c * (0.3059659442682285_f64 + (s_c * (0.06022003633913529_f64 + (0.012905024445434484_f64 * s_c)))))))))))) / (1.0_f64 + (s_c * (1.5811748671463468_f64 + (s_c * (1.6014471324762964_f64 + (s_c * (0.8300401858368824_f64 + (s_c * (0.35307186381340155_f64 + (s_c * (0.06959016841317585_f64 + (0.014419758064389_f64 * s_c)))))))))))));
}

#[rustfmt::skip]
fn bl_over_bmax(mut s_c: f64) -> f64 {
if (s_c < 2.6267851073127395_f64) {
if (s_c < 0.7099295739719539_f64) {
let mut g: f64 = ((0.08074107237288286_f64 + (s_c * (0.0980789117863589_f64 + (s_c * (0.039760631445677055_f64 + (s_c * (0.005971692845958919_f64 + (s_c * ((-6.40363993414798e-06_f64) + (4.5425102093616064e-07_f64 * s_c)))))))))) / (1.0_f64 + (s_c * (1.8594977672287665_f64 + (s_c * (1.365880147571179_f64 + (s_c * (0.4613270710865565_f64 + (0.06125459704983172_f64 * s_c)))))))));
return ((s_c * s_c) * (0.07560996640296362_f64 + (s_c * ((s_c * g) - 0.09672719281339437_f64))));
}
return ((1.979573792759858e-09_f64 + (s_c * ((-2.7081288564685587e-08_f64) + (s_c * (0.07561014227254904_f64 + (s_c * (0.06917130174466835_f64 + (s_c * (0.029537058950963018_f64 + (s_c * (0.006584925270230231_f64 + (0.0006971140063983471_f64 * s_c)))))))))))) / (1.0_f64 + (s_c * (2.194144852558658_f64 + (s_c * (2.129710354999518_f64 + (s_c * (1.1571483187179783_f64 + (s_c * (0.3783162225306046_f64 + (s_c * (0.07171486244882935_f64 + (0.00663619758278612_f64 * s_c)))))))))))));
}
if (s_c < 7.348469228349534_f64) {
return (((-9.332511535483788e-05_f64) + (s_c * (0.0005311803397279465_f64 + (s_c * (0.07411485544834501_f64 + (s_c * (0.07403965818682282_f64 + (s_c * (0.039225177407687606_f64 + (s_c * (0.01002291337825409_f64 + (0.0017012579407246055_f64 * s_c)))))))))))) / (1.0_f64 + (s_c * (2.2217238132228134_f64 + (s_c * (2.3441816707087404_f64 + (s_c * (1.391232364627114_f64 + (s_c * (0.5323125844350184_f64 + (s_c * (0.11744005919716101_f64 + (0.016195405895930937_f64 * s_c)))))))))))));
}
return ((0.0014500072297240604_f64 + (s_c * ((-0.0015116692485011196_f64) + (s_c * (0.07168217831093633_f64 + (s_c * (0.039216108578204636_f64 + (s_c * (0.029342405658628445_f64 + (s_c * (0.005183252617163152_f64 + (0.0016930208078421475_f64 * s_c)))))))))))) / (1.0_f64 + (s_c * (1.6176313502305415_f64 + (s_c * (1.6823159175281532_f64 + (s_c * (0.8487830756737222_f64 + (s_c * (0.3754374213737579_f64 + (s_c * (0.07126137099644303_f64 + (0.016116992546788677_f64 * s_c)))))))))))));
}

#[rustfmt::skip]
fn compute_f_lower_map_and_first_two_derivatives(mut x: f64, mut s: f64, f: &mut f64, fp: &mut f64, fpp: &mut f64) {
let mut ax: f64 = (x).abs();
let mut z: f64 = ((0.5773502691896257_f64 * ax) / s);
let mut y: f64 = (z * z);
let mut s2: f64 = (s * s);
let mut Phi: f64 = (0.5_f64 * erfc_cody(((1.0_f64 / 1.4142135623730951_f64) * z)));
let mut phi: f64 = norm_pdf(z);
((*fpp) = (((((0.5235987755982989_f64 * y) / (s2 * s)) * Phi) * ((((8.0_f64 * 1.7320508075688772_f64) * s) * ax) + (((((3.0_f64 * s2) * (s2 - 8.0_f64)) - ((8.0_f64 * x) * x)) * Phi) / phi))) * (((2.0_f64 * y) + (0.25_f64 * s2))).exp()));
{
let mut Phi2: f64 = (Phi * Phi);
((*fp) = (((6.283185307179586_f64 * y) * Phi2) * ((y + ((0.125_f64 * s) * s))).exp()));
((*f) = ((1.2091995761561452_f64 * ax) * (Phi2 * Phi)));
}
}

#[rustfmt::skip]
fn compute_f_upper_map_and_first_two_derivatives(mut x: f64, mut s: f64, f: &mut f64, fp: &mut f64, fpp: &mut f64) {
((*f) = (0.5_f64 * erfc_cody(((0.5_f64 / 1.4142135623730951_f64) * s))));
let mut w: f64 = square((x / s));
((*fp) = ((-0.5_f64) * ((0.5_f64 * w)).exp()));
((*fpp) = (((1.2533141373155003_f64 * ((w + ((0.125_f64 * s) * s))).exp()) * w) / s));
}

#[rustfmt::skip]
fn convex_rational_cubic_control_parameter_to_fit_second_derivative_at_left_side(mut x_l: f64, mut x_r: f64, mut y_l: f64, mut y_r: f64, mut d_l: f64, mut d_r: f64, mut second_derivative_l: f64, mut preferShapePreservationOverSmoothness: bool) -> f64 {
let mut r: f64 = rational_cubic_control_parameter_to_fit_second_derivative_at_left_side(x_l, x_r, y_l, y_r, d_l, d_r, second_derivative_l);
let mut r_min: f64 = minimum_rational_cubic_control_parameter(d_l, d_r, ((y_r - y_l) / (x_r - x_l)), preferShapePreservationOverSmoothness);
return cxx_max(r, r_min);
}

#[rustfmt::skip]
fn convex_rational_cubic_control_parameter_to_fit_second_derivative_at_right_side(mut x_l: f64, mut x_r: f64, mut y_l: f64, mut y_r: f64, mut d_l: f64, mut d_r: f64, mut second_derivative_r: f64, mut preferShapePreservationOverSmoothness: bool) -> f64 {
let mut r: f64 = rational_cubic_control_parameter_to_fit_second_derivative_at_right_side(x_l, x_r, y_l, y_r, d_l, d_r, second_derivative_r);
let mut r_min: f64 = minimum_rational_cubic_control_parameter(d_l, d_r, ((y_r - y_l) / (x_r - x_l)), preferShapePreservationOverSmoothness);
return cxx_max(r, r_min);
}

#[rustfmt::skip]
fn householder_factor3(mut nu: f64, mut h2: f64, mut h3: f64) -> f64 {
return householder3_factor(nu, h2, h3);
}

#[rustfmt::skip]
fn householder_factor4(mut nu: f64, mut h2: f64, mut h3: f64, mut h4: f64) -> f64 {
return householder4_factor(nu, h2, h3, h4);
}

#[rustfmt::skip]
fn implied_volatility_output(mut _unused: i32, mut volatility: f64) -> f64 {
return volatility;
}

#[rustfmt::skip]
fn inv_normalised_vega(mut x: f64, mut s: f64) -> f64 {

let mut h: f64 = (x / s);
let mut t: f64 = (0.5_f64 * s);
return (2.5066282746310007_f64 * ((0.5_f64 * ((h * h) + (t * t)))).exp());
}

#[rustfmt::skip]
fn inverse_f_lower_map(mut x: f64, mut f: f64) -> f64 {
return ((x / (1.7320508075688772_f64 * inverse_norm_cdf(((0.9386434874273836_f64 * (f).cbrt()) / ((x).abs()).cbrt()))))).abs();
}

#[rustfmt::skip]
fn inverse_f_upper_map(mut f: f64) -> f64 {
return ((-2.0_f64) * inverse_norm_cdf(f));
}

#[rustfmt::skip]
fn normalised_black(mut thetax: f64, mut s: f64) -> f64 {


if ((thetax < (s * ((-13) as f64))) && (((s * ((0.5_f64 * s) - (((2.0_f64 * SIXTEENTH_ROOT_DBL_EPSILON) + 0.5_f64) + ((-13) as f64)))) + thetax) < 0.0_f64)) {
return (asymptotic_expansion_of_scaled_normalised_black((thetax / s), (0.5_f64 * s)) * normalised_vega(thetax, s));
}
if (((s * (s - (2.0_f64 * (2.0_f64 * SIXTEENTH_ROOT_DBL_EPSILON)))) - (thetax / ((-13) as f64))) < 0.0_f64) {
return (small_t_expansion_of_scaled_normalised_black((thetax / s), (0.5_f64 * s)) * normalised_vega(thetax, s));
}
return normalised_black_with_optimal_use_of_codys_functions(thetax, s);
}

#[rustfmt::skip]
fn normalised_vega(mut x: f64, mut s: f64) -> f64 {

let mut h: f64 = (x / s);
let mut t: f64 = (0.5_f64 * s);
return ((1.0_f64 / 2.5066282746310007_f64) * (((-0.5_f64) * ((h * h) + (t * t)))).exp());
}

#[rustfmt::skip]
fn one_minus_erfcx(mut x: f64) -> f64 {
if ((x < ((-1.0_f64) / 5.0_f64)) || (x > (1.0_f64 / 3.0_f64))) {
return (1.0_f64 - erfcx_cody(x));
}
return (x * (1.1283791670955126_f64 - ((x * (1.0000000000000002_f64 + (x * (1.1514967181784757_f64 + (x * (0.5768900120887374_f64 + (x * (0.1406918874460965_f64 + (0.014069285713634565_f64 * x))))))))) / (1.0_f64 + (x * (1.9037494962421564_f64 + (x * (1.5089908593742722_f64 + (x * (0.6248608165864026_f64 + (x * (0.1358008134514386_f64 + (0.012463320728346347_f64 * x)))))))))))));
}

#[rustfmt::skip]
fn rational_cubic_interpolation(mut x: f64, mut x_l: f64, mut x_r: f64, mut y_l: f64, mut y_r: f64, mut d_l: f64, mut d_r: f64, mut r: f64) -> f64 {
let mut h: f64 = (x_r - x_l);
if ((h).abs() <= 0.0_f64) {
return (0.5_f64 * (y_l + y_r));
}
let mut t: f64 = ((x - x_l) / h);
if (!(r >= maximum_rational_cubic_control_parameter_value)) {
let mut t: f64 = ((x - x_l) / h);
let mut omt: f64 = (1.0_f64 - t);
let mut t2: f64 = (t * t);
let mut omt2: f64 = (omt * omt);
return ((((((y_r * t2) * t) + ((((r * y_r) - (h * d_r)) * t2) * omt)) + ((((r * y_l) + (h * d_l)) * t) * omt2)) + ((y_l * omt2) * omt)) / (1.0_f64 + (((r - 3.0_f64) * t) * omt)));
}
return ((y_r * t) + (y_l * (1.0_f64 - t)));
}

#[rustfmt::skip]
fn scaled_normalised_black_and_ln_vega(mut thetax: f64, mut s: f64) -> (f64, f64) {


if ((thetax < (s * ((-13) as f64))) && (((s * ((0.5_f64 * s) - (((2.0_f64 * SIXTEENTH_ROOT_DBL_EPSILON) + 0.5_f64) + ((-13) as f64)))) + thetax) < 0.0_f64)) {
return (asymptotic_expansion_of_scaled_normalised_black((thetax / s), (0.5_f64 * s)), ln_normalised_vega(thetax, s));
}
if (((s * (s - (2.0_f64 * (2.0_f64 * SIXTEENTH_ROOT_DBL_EPSILON)))) - (thetax / ((-13) as f64))) < 0.0_f64) {
return (small_t_expansion_of_scaled_normalised_black((thetax / s), (0.5_f64 * s)), ln_normalised_vega(thetax, s));
}
let mut ln_vega: f64 = ln_normalised_vega(thetax, s);
return ((normalised_black_with_optimal_use_of_codys_functions(thetax, s) * ((-ln_vega)).exp()), ln_vega);
}

#[rustfmt::skip]
fn asymptotic_expansion_of_scaled_normalised_black(mut h: f64, mut t: f64) -> f64 {

let mut e: f64 = square((t / h));
let mut r: f64 = ((h + t) * (h - t));
let mut q: f64 = square((h / r));
let mut omega: f64 = 0.0_f64;
let mut thresholds: [f64; 12] = [12.347_f64, 12.958_f64, 13.729_f64, 14.718_f64, 16.016_f64, 17.769_f64, 20.221_f64, 23.816_f64, 29.419_f64, 38.93_f64, 57.171_f64, 99.347_f64];
{
let sought = ((((-h) - t) + (2.0_f64 * SIXTEENTH_ROOT_DBL_EPSILON)) + 0.5_f64);
let selected = thresholds.partition_point(|v| !(sought < *v));
if selected == 0 { (omega = (q * ((1.26653197415257e+19_f64 + (e * (2.093999530598916e+21_f64 + (e * (9.108897958105285e+22_f64 + (e * (1.6396016324589512e+24_f64 + (e * (1.4801959181921086e+25_f64 + (e * (7.427892244018582e+25_f64 + (e * (2.199798856882426e+26_f64 + (e * (3.9805884076920094e+26_f64 + (e * (4.478161958653511e+26_f64 + (e * (3.142569795546323e+26_f64 + (e * (1.36178024473674e+26_f64 + (e * (3.5524702036610607e+25_f64 + (e * (5.328705305491592e+24_f64 + (e * (4.250819047115799e+23_f64 + (e * (1.570499647949187e+22_f64 + (e * (2.026451158644112e+20_f64 + (3.8379756792502125e+17_f64 * e)))))))))))))))))))))))))))))))) + omega))); }
if selected <= 1 { (omega = (q * (((-3.8379756792502125e+17_f64) + (e * ((-5.565064734912808e+19_f64) + (e * ((-2.1035944697970415e+21_f64) + (e * ((-3.2555628699239928e+22_f64) + (e * ((-2.4959315336083945e+23_f64) + (e * ((-1.0482912441155257e+24_f64) + (e * ((-2.553529953614742e+24_f64) + (e * ((-3.720857932410053e+24_f64) + (e * ((-3.283109940361811e+24_f64) + (e * ((-1.747152073525876e+24_f64) + (e * ((-5.4910493739384675e+23_f64) + (e * ((-9.766688609771979e+22_f64) + (e * ((-9.11557603578718e+21_f64) + (e * ((-3.8955453144389655e+20_f64) + (e * ((-5.756963518875318e+18_f64) - (1.238056670725875e+16_f64 * e)))))))))))))))))))))))))))))) + omega))); }
if selected <= 2 { (omega = (q * ((1.238056670725875e+16_f64 + (e * (1.5599514051146025e+18_f64 + (e * (5.069842066622458e+19_f64 + (e * (6.66322100184666e+20_f64 + (e * (4.275566809518273e+21_f64 + (e * (1.477013988742676e+22_f64 + (e * (2.8972197471490954e+22_f64 + (e * (3.311108282456109e+22_f64 + (e * (2.215520983114014e+22_f64 + (e * (8.551133619036546e+21_f64 + (e * (1.8323857755078313e+21_f64 + (e * (2.0279368266489833e+20_f64 + (e * (1.0139684133244916e+19_f64 + (e * (1.733279339016225e+17_f64 + (426916093353750.0_f64 * e)))))))))))))))))))))))))))) + omega))); }
if selected <= 3 { (omega = (q * (((-426916093353750.0_f64) + (e * ((-4.624924344665625e+16_f64) + (e * ((-1.2764791191277125e+18_f64) + (e * ((-1.4041270310404837e+19_f64) + (e * ((-7.410670441602553e+19_f64) + (e * ((-2.0615137773912556e+20_f64) + (e * ((-3.171559657525009e+20_f64) + (e * ((-2.7486850365216742e+20_f64) + (e * ((-1.3339206794884596e+20_f64) + (e * ((-3.5103175776012095e+19_f64) + (e * ((-4.680423436801613e+18_f64) + (e * ((-2.774954606799375e+17_f64) + (e * ((-5549909213598750.0_f64) - (15811707161250.0_f64 * e)))))))))))))))))))))))))) + omega))); }
if selected <= 4 { (omega = (q * ((15811707161250.0_f64 + (e * (1454677058835000.0_f64 + (e * (3.36030400590885e+16_f64 + (e * (3.04027505296515e+17_f64 + (e * (1.2921168975101888e+18_f64 + (e * (2.81916414002223e+18_f64 + (e * (3.289024830025935e+18_f64 + (e * (2.067387036016302e+18_f64 + (e * (6.840618869171588e+17_f64 + (e * (1.12010133530295e+17_f64 + (e * (8000723823592500.0_f64 + (e * (189740485935000.0_f64 + (632468286450.0_f64 * e)))))))))))))))))))))))) + omega))); }
if selected <= 5 { (omega = (q * (((-632468286450.0_f64) + (e * ((-48700058056650.0_f64) + (e * ((-925301103076350.0_f64) + (e * ((-6741479465270550.0_f64) + (e * ((-2.24715982175685e+16_f64) + (e * ((-3.71802806872497e+16_f64) + (e * ((-3.14602375045959e+16_f64) + (e * ((-1.34829589305411e+16_f64) + (e * ((-2775903309229050.0_f64) + (e * ((-243500290283250.0_f64) + (e * ((-6957151150950.0_f64) - (27498621150.0_f64 * e)))))))))))))))))))))) + omega))); }
if selected <= 6 { (omega = (q * ((27498621150.0_f64 + (e * (1741579339500.0_f64 + (e * (26646163894350.0_f64 + (e * (152263793682000.0_f64 + (e * (384889034029500.0_f64 + (e * (461866840835400.0_f64 + (e * (266461638943500.0_f64 + (e * (71056437051600.0_f64 + (e * (7837107027750.0_f64 + (e * (274986211500.0_f64 + (1309458150.0_f64 * e)))))))))))))))))))) + omega))); }
if selected <= 7 { (omega = (q * (((-1309458150.0_f64) + (e * ((-66782365650.0_f64) + (e * ((-801388387800.0_f64) + (e * ((-3472683013800.0_f64) + (e * ((-6366585525300.0_f64) + (e * ((-5209024520700.0_f64) + (e * ((-1869906238200.0_f64) + (e * ((-267129462600.0_f64) + (e * ((-11785123350.0_f64) - (68918850.0_f64 * e)))))))))))))))))) + omega))); }
if selected <= 8 { (omega = (q * ((68918850.0_f64 + (e * (2756754000.0_f64 + (e * (25086461400.0_f64 + (e * (78843164400.0_f64 + (e * (98553955500.0_f64 + (e * (50172922800.0_f64 + (e * (9648639000.0_f64 + (e * (551350800.0_f64 + (4054050.0_f64 * e)))))))))))))))) + omega))); }
if selected <= 9 { (omega = (q * (((-4054050.0_f64) + (e * ((-122972850.0_f64) + (e * ((-811620810.0_f64) + (e * ((-1739187450.0_f64) + (e * ((-1352701350.0_f64) + (e * ((-368918550.0_f64) + (e * ((-28378350.0_f64) - (270270.0_f64 * e)))))))))))))) + omega))); }
if selected <= 10 { (omega = (q * ((270270.0_f64 + (e * (5945940.0_f64 + (e * (26756730.0_f64 + (e * (35675640.0_f64 + (e * (14864850.0_f64 + (e * (1621620.0_f64 + (20790.0_f64 * e)))))))))))) + omega))); }
if selected <= 11 { (omega = (q * (((-20790.0_f64) + (e * ((-311850.0_f64) + (e * ((-873180.0_f64) + (e * ((-623700.0_f64) + (e * ((-103950.0_f64) - (1890.0_f64 * e)))))))))) + omega))); }
(omega = (2.0_f64 + (q * ((((-6) as f64) - (2.0_f64 * e)) + (q * ((30.0_f64 + (e * (60.0_f64 + (6.0_f64 * e)))) + (q * (((-210.0_f64) + (e * ((-1050.0_f64) + (e * ((-630.0_f64) - (30.0_f64 * e)))))) + (q * ((1890.0_f64 + (e * (17640.0_f64 + (e * (26460.0_f64 + (e * (7560.0_f64 + (210.0_f64 * e)))))))) + omega))))))))));
}
let mut bx: f64 = ((t / r) * omega);
return bx;
}

#[rustfmt::skip]
fn householder3_factor(mut nu: f64, mut h2: f64, mut h3: f64) -> f64 {
return ((1.0_f64 + ((0.5_f64 * h2) * nu)) / (1.0_f64 + (nu * (h2 + ((h3 * nu) * (1.0_f64 / 6.0_f64))))));
}

#[rustfmt::skip]
fn householder4_factor(mut nu: f64, mut h2: f64, mut h3: f64, mut h4: f64) -> f64 {
return ((1.0_f64 + (nu * (h2 + ((nu * h3) * (1.0_f64 / 6.0_f64))))) / (1.0_f64 + (nu * ((1.5_f64 * h2) + (nu * ((((h2 * h2) * 0.25_f64) + (h3 * (1.0_f64 / 3.0_f64))) + ((nu * h4) * (1.0_f64 / 24.0_f64))))))));
}

#[rustfmt::skip]
fn ln_normalised_vega(mut x: f64, mut s: f64) -> f64 {

let mut h: f64 = (x / s);
let mut t: f64 = (0.5_f64 * s);
return ((-(1.8378770664093456_f64 * 0.5_f64)) - (0.5_f64 * ((h * h) + (t * t))));
}

#[rustfmt::skip]
fn minimum_rational_cubic_control_parameter(mut d_l: f64, mut d_r: f64, mut s: f64, mut preferShapePreservationOverSmoothness: bool) -> f64 {
let mut monotonic: bool = (((d_l * s) >= 0.0_f64) && ((d_r * s) >= 0.0_f64));
let mut convex: bool = ((d_l <= s) && (s <= d_r));
let mut concave: bool = ((d_l >= s) && (s >= d_r));
if (((!monotonic) && (!convex)) && (!concave)) {
return minimum_rational_cubic_control_parameter_value;
}
let mut d_r_m_d_l: f64 = (d_r - d_l);
let mut d_r_m_s: f64 = (d_r - s);
let mut s_m_d_l: f64 = (s - d_l);
let mut r1: f64 = (-1.7976931348623157e+308_f64);
let mut r2: f64 = r1;
if monotonic {
if (!is_zero(s)) {
(r1 = ((d_r + d_l) / s));
} else {
if preferShapePreservationOverSmoothness {
(r1 = maximum_rational_cubic_control_parameter_value);
}
}
}
if (convex || concave) {
if (!(is_zero(s_m_d_l) || is_zero(d_r_m_s))) {
(r2 = cxx_max(((d_r_m_d_l / d_r_m_s)).abs(), ((d_r_m_d_l / s_m_d_l)).abs()));
} else {
if preferShapePreservationOverSmoothness {
(r2 = maximum_rational_cubic_control_parameter_value);
}
}
} else {
if (monotonic && preferShapePreservationOverSmoothness) {
(r2 = maximum_rational_cubic_control_parameter_value);
}
}
return cxx_max(minimum_rational_cubic_control_parameter_value, cxx_max(r1, r2));
}

#[rustfmt::skip]
fn norm_pdf(mut x: f64) -> f64 {
return ((1.0_f64 / 2.5066282746310007_f64) * ((((-0.5_f64) * x) * x)).exp());
}

#[rustfmt::skip]
fn normalised_black_with_optimal_use_of_codys_functions(mut thetax: f64, mut s: f64) -> f64 {
let mut codys_threshold: f64 = 0.46875_f64;
let mut h: f64 = (thetax / s);
let mut t: f64 = (0.5_f64 * s);
let mut q1: f64 = ((-(1.0_f64 / 1.4142135623730951_f64)) * (h + t));
let mut q2: f64 = ((-(1.0_f64 / 1.4142135623730951_f64)) * (h - t));
let mut two_b: f64 = 0.0;
if (q1 < codys_threshold) {
if (q2 < codys_threshold) {
(two_b = ((((0.5_f64 * thetax)).exp() * erfc_cody(q1)) - ((((-0.5_f64) * thetax)).exp() * erfc_cody(q2))));
} else {
(two_b = ((((0.5_f64 * thetax)).exp() * erfc_cody(q1)) - ((((-0.5_f64) * ((h * h) + (t * t)))).exp() * erfcx_cody(q2))));
}
} else {
if (q2 < codys_threshold) {
(two_b = (((((-0.5_f64) * ((h * h) + (t * t)))).exp() * erfcx_cody(q1)) - ((((-0.5_f64) * thetax)).exp() * erfc_cody(q2))));
} else {
(two_b = ((((-0.5_f64) * ((h * h) + (t * t)))).exp() * (erfcx_cody(q1) - erfcx_cody(q2))));
}
}
return cxx_max((0.5_f64 * two_b), 0.0_f64);
}

#[rustfmt::skip]
fn rational_cubic_control_parameter_to_fit_second_derivative_at_left_side(mut x_l: f64, mut x_r: f64, mut y_l: f64, mut y_r: f64, mut d_l: f64, mut d_r: f64, mut second_derivative_l: f64) -> f64 {
let mut h: f64 = (x_r - x_l);
let mut numerator: f64 = (((0.5_f64 * h) * second_derivative_l) + (d_r - d_l));
let mut denominator: f64 = (((y_r - y_l) / h) - d_l);
if is_zero(denominator) {
return (if (numerator > 0.0_f64) { maximum_rational_cubic_control_parameter_value } else { minimum_rational_cubic_control_parameter_value });
}
return (numerator / denominator);
}

#[rustfmt::skip]
fn rational_cubic_control_parameter_to_fit_second_derivative_at_right_side(mut x_l: f64, mut x_r: f64, mut y_l: f64, mut y_r: f64, mut d_l: f64, mut d_r: f64, mut second_derivative_r: f64) -> f64 {
let mut h: f64 = (x_r - x_l);
let mut numerator: f64 = (((0.5_f64 * h) * second_derivative_r) + (d_r - d_l));
let mut denominator: f64 = (d_r - ((y_r - y_l) / h));
if is_zero(denominator) {
return (if (numerator > 0.0_f64) { maximum_rational_cubic_control_parameter_value } else { minimum_rational_cubic_control_parameter_value });
}
return (numerator / denominator);
}

#[rustfmt::skip]
fn small_t_expansion_of_scaled_normalised_black(mut h: f64, mut t: f64) -> f64 {
let mut a: f64 = Yprime(h);
let mut h_sqr: f64 = (h * h);
let mut t_sqr: f64 = (t * t);
return (t * ((2.0_f64 * a) + (t_sqr * (((((-1) as f64) + (a * (3.0_f64 + h_sqr))) / 3.0_f64) + (t_sqr * ((((((-7) as f64) - h_sqr) + (a * (15.0_f64 + (h_sqr * (10.0_f64 + h_sqr))))) / 60.0_f64) + (t_sqr * ((((((-57) as f64) + ((((-18) as f64) - h_sqr) * h_sqr)) + (a * (105.0_f64 + (h_sqr * (105.0_f64 + (h_sqr * (21.0_f64 + h_sqr))))))) / 2520.0_f64) + (t_sqr * ((((((-561) as f64) + (h_sqr * (((-285) as f64) + ((((-33) as f64) - h_sqr) * h_sqr)))) + (a * (945.0_f64 + (h_sqr * (1260.0_f64 + (h_sqr * (378.0_f64 + (h_sqr * (36.0_f64 + h_sqr))))))))) / 181440.0_f64) + (t_sqr * ((((((-6555) as f64) + (h_sqr * (((-4680) as f64) + (h_sqr * (((-840) as f64) + ((((-52) as f64) - h_sqr) * h_sqr)))))) + (a * (10395.0_f64 + (h_sqr * (17325.0_f64 + (h_sqr * (6930.0_f64 + (h_sqr * (990.0_f64 + (h_sqr * (55.0_f64 + h_sqr))))))))))) / 19958400.0_f64) + ((((((-89055) as f64) + (h_sqr * (((-82845) as f64) + (h_sqr * (((-20370) as f64) + (h_sqr * (((-1926) as f64) + ((((-75) as f64) - h_sqr) * h_sqr)))))))) + (a * (135135.0_f64 + (h_sqr * (270270.0_f64 + (h_sqr * (135135.0_f64 + (h_sqr * (25740.0_f64 + (h_sqr * (2145.0_f64 + (h_sqr * (78.0_f64 + h_sqr))))))))))))) / 3113510400.0_f64) * t_sqr)))))))))))));
}

#[rustfmt::skip]
fn square(mut x: f64) -> f64 {
return (x * x);
}

#[rustfmt::skip]
fn Yprime(mut h: f64) -> f64 {
if (h < ((-4) as f64)) {
let mut w: f64 = (1.0_f64 / (h * h));
return (w * (1.0_f64 + Yprime_tail_expansion_rational_function_part(w)));
}
if (h <= (-0.46875_f64)) {
return ((1.0000000000594318_f64 - (h * (0.6191144987969411_f64 - (h * (0.22180844736576014_f64 - (h * (0.04565090035135299_f64 - (h * (0.0055455210077353795_f64 - (h * (0.00030717392274913903_f64 - (h * (4.2766597835908714e-08_f64 + (8.45924364065806e-10_f64 * h)))))))))))))) / (1.0_f64 - (h * (1.8724286369589163_f64 - (h * (1.5685497236077652_f64 - (h * (0.7657648983658903_f64 - (h * (0.2367770140309464_f64 - (h * (0.04676254890319496_f64 - (h * (0.005529045357693659_f64 - (0.00030822020417927147_f64 * h)))))))))))))));
}
return (1.0_f64 + ((h * 1.2533141373155003_f64) * erfcx_cody(((-(1.0_f64 / 1.4142135623730951_f64)) * h))));
}

#[rustfmt::skip]
fn is_zero(mut x: f64) -> bool {
return ((x).abs() < 2.2250738585072014e-308_f64);
}

#[rustfmt::skip]
fn Yprime_tail_expansion_rational_function_part(mut w: f64) -> f64 {
return ((w * ((-2.999999999999466_f64) + (w * ((-175.56263323542206_f64) + (w * ((-3473.5035445495632_f64) + (w * ((-27805.745693864308_f64) + (w * ((-83836.02146074198_f64) - (66818.24903261685_f64 * w))))))))))) / (1.0_f64 + (w * (63.520877744831736_f64 + (w * (1440.4389037604337_f64 + (w * (14562.545638507034_f64 + (w * (66886.79416565168_f64 + (w * (125699.70380923909_f64 + (69286.51867980375_f64 * w)))))))))))));
}
